# Generated by Django 4.2.22 on 2025-10-03 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EvalData', '0055_alter_market_domainname_alter_market_marketid'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairwiseassessmentresult',
            name='metadata',
            field=models.TextField(blank=True, help_text='(JSONL metadata)', null=True, verbose_name='Metadata'),
        ),
    ]
