# Generated by Django on 2025-11-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EvalData', '0056_pairwiseassessmentresult_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairwiseassessmentdocumentresult',
            name='browser_info',
            field=models.CharField(
                blank=True,
                help_text='(browser type and version when available)',
                max_length=255,
                null=True,
                verbose_name='Browser info',
            ),
        ),
    ]
